// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bshvrediyfryqhdwpasy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzaHZyZWRpeWZyeXFoZHdwYXN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NzQxODIsImV4cCI6MjA2NjQ1MDE4Mn0.12I6q-2Y7oge66JJKnjTsBB9Esfd2rUaaCv91obnWWk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);